from Vehicle import Vehicle
from Ship import Ship
from Airplane import Airplane

#instalasi Objek dan mengisi data menggunakan setter
#memasukan data dammy keseluruhan
#Vehicle
d1 = Vehicle()
d1.setname("Motor Honda")
d1.setfueltype("Bensin")
d1.setmaxpassengers(2)

d2 = Vehicle()
d2.setname("Mobil Lamborgini")
d2.setfueltype("Bensin")
d2.setmaxpassengers(2)

d3 = Vehicle()
d3.setname("Mobil Fortuner")
d3.setfueltype("Bensin")
d3.setmaxpassengers(7)

d4 = Vehicle()
d4.setname("Formula 1 car")
d4.setfueltype("Etanol 10")
d4.setmaxpassengers(1)

d5 = Vehicle()
d5.setname("Bell 412")
d5.setfueltype("Avtur jet A-1")
d5.setmaxpassengers(15)

#Ship
s1 = Ship()
s1.setname("KRI Golok")
s1.settype("Kapal perang")
s1.setage(10)
s1.setfueltype("solar")
s1.setmaxpassengers(25)
s1.setcountryOfManufacture("Indonesia")

s2 = Ship()
s2.setname("RMS Titanic")
s2.settype("Kapal Penumpang")
s2.setage(110)
s2.setfueltype("batubara")
s2.setmaxpassengers(2435)
s2.setcountryOfManufacture("England")

s3 = Ship()
s3.setname("USS Seawolf")
s3.settype("Kapal Selam")
s3.setage(25)
s3.setfueltype("Uranium")
s3.setmaxpassengers(140)
s3.setcountryOfManufacture("USA")

s4 = Ship()
s4.setname("HSC Jonathan Swift.")
s4.settype("Kapal Ferry")
s4.setage(23)
s4.setfueltype("diesel")
s4.setmaxpassengers(800)
s4.setcountryOfManufacture("Australia")

s5 = Ship()
s5.setname("HSC Dolphin Jet")
s5.settype("Kapal Ferry")
s5.setage(19)
s5.setfueltype("solar")
s5.setmaxpassengers(774)
s5.setcountryOfManufacture("Australia")

#Airplane
a1 = Airplane()
a1.setname("EADS CASA C-295")
a1.settype("Millitary transport aircraft")
a1.setage(25)
a1.setfueltype("Avtur")
a1.setmaxpassengers(71)
a1.setWingsLength(26)

a2 = Airplane()
a2.setname("Airbus A400M")
a2.settype("Millitary transport aircraft")
a2.setage(15)
a2.setfueltype("Avtur")
a2.setmaxpassengers(462)
a2.setWingsLength(46)

a3 = Airplane()
a3.setname("Eurofighter Typhoon")
a3.settype("Pesawat tempur")
a3.setage(28)
a3.setfueltype("Avgas")
a3.setmaxpassengers(2)
a3.setWingsLength(11)

a4 = Airplane()
a4.setname("CASA C-212")
a4.settype("Pesawat angkut menengah")
a4.setage(53)
a4.setfueltype("Avtur")
a4.setmaxpassengers(28)
a4.setWingsLength(20)

a5 = Airplane()
a5.setname("Embraer C-390 Millennium")
a5.settype("Pesawat angkut menengah")
a5.setage(8)
a5.setfueltype("Avtur")
a5.setmaxpassengers(362)
a5.setWingsLength(34)



#get nilai yang ada pada objek data keseluruhan
#menampilkan data dammy
print("--- data Kendaraan  ---")
print("-----------------------------")
print("Vehicle :")
print("Name	        : "+ str (d1.getname()))
print("Fuel Type	: "+ str(d1.getfueltype()))
print("MaxPassengers	: "+ str(d1.getmaxpassengers()))
print("=====================")
print("Vehicle :")
print("Name	        : "+ str (d2.getname()))
print("Fuel Type	: "+ str(d2.getfueltype()))
print("MaxPassengers	: "+ str(d2.getmaxpassengers()))
print("=====================")
print("Vehicle :")
print("Name	        : "+ str (d3.getname()))
print("Fuel Type	: "+ str(d3.getfueltype()))
print("MaxPassengers	: "+ str(d3.getmaxpassengers()))
print("=====================")
print("Vehicle :")
print("Name	        : "+ str (d4.getname()))
print("Fuel Type	: "+ str(d4.getfueltype()))
print("MaxPassengers	: "+ str(d4.getmaxpassengers()))
print("=====================")
print("Vehicle :")
print("Name	        : "+ str (d5.getname()))
print("Fuel Type	: "+ str(d5.getfueltype()))
print("MaxPassengers	: "+ str(d5.getmaxpassengers()))
print("=====================")
print("")
print("-----------------------------")
print("Ship :")
print("Name	                : "+ str (s1.getname()))
print("Age	                : "+ str(s1.getage()))
print("Type	                : "+ str(s1.gettype()))
print("Fuel Type	        : "+ str(s1.getfueltype()))
print("MaxPassengers	        : "+ str(s1.getmaxpassengers()))
print("Country of Manufacture	: "+ str(s1.getcountryOfManufacture()))
s1.move()
print("=====================")
print("Name	                : "+ str (s2.getname()))
print("Age	                : "+ str(s2.getage()))
print("Type	                : "+ str(s2.gettype()))
print("Fuel Type	        : "+ str(s2.getfueltype()))
print("MaxPassengers	        : "+ str(s2.getmaxpassengers()))
print("Country of Manufacture	: "+ str(s2.getcountryOfManufacture()))
s2.move()
print("=====================")
print("Name	                : "+ str (s3.getname()))
print("Age                 	: "+ str(s3.getage()))
print("Type	                : "+ str(s3.gettype()))
print("Fuel Type	        : " + str(s3.getfueltype()))
print("MaxPassengers	        : "+ str(s3.getmaxpassengers()))
print("Country of Manufacture	: "+ str(s3.getcountryOfManufacture()))
s3.move()
print("=====================")
print("Name	                  : "+ str (s4.getname()))
print("Age	                : "+ str(s4.getage()))
print("Type	                : "+ str(s4.gettype()))
print("Fuel Type	        : "+ str(s4.getfueltype()))
print("MaxPassengers	        : "+ str(s4.getmaxpassengers()))
print("Country of Manufacture	: "+ str(s4.getcountryOfManufacture()))
s4.move()
print("=====================")
print("Name	                : "+ str (s5.getname()))
print("Age	                : "+ str(s5.getage()))
print("Type	                : "+ str(s5.gettype()))
print("Fuel Type	        : "+ str(s5.getfueltype()))
print("MaxPassengers	        : "+ str(s5.getmaxpassengers()))
print("Country of Manufacture	: "+ str(s5.getcountryOfManufacture()))
s5.move()
print("=====================")
print("")
print("-----------------------------")
print("Airplane :")
print("Name	                : "+ str (a1.getname()))
print("Age	                : "+ str(a1.getage()))
print("Type	                : "+ str(a1.gettype()))
print("Fuel Type	        : "+ str(a1.getfueltype()))
print("MaxPassengers	        : "+ str(a1.getmaxpassengers()))
print("Wings length     	: "+ str(a1.getWingsLength()))
a1.move()
print("=====================")
print("Name	                : "+ str (a2.getname()))
print("Age	                : "+ str(a2.getage()))
print("Type	                : "+ str(a2.gettype()))
print("Fuel Type	        : "+ str(a2.getfueltype()))
print("MaxPassengers	        : "+ str(a2.getmaxpassengers()))
print("Wings length     	: "+ str(a2.getWingsLength()))
a2.move()
print("=====================")
print("Name	                : "+ str (a3.getname()))
print("Age	                : "+ str(a3.getage()))
print("Type	                : "+ str(a3.gettype()))
print("Fuel Type	        : "+ str(a3.getfueltype()))
print("MaxPassengers	        : "+ str(a3.getmaxpassengers()))
print("Wings length     	: "+ str(a3.getWingsLength()))
a3.move()
print("=====================")
print("Name	                : "+ str (a4.getname()))
print("Age	                : "+ str(a4.getage()))
print("Type	                : "+ str(a4.gettype()))
print("Fuel Type	        : "+ str(a4.getfueltype()))
print("MaxPassengers	        : "+ str(a4.getmaxpassengers()))
print("Wings length     	: "+ str(a4.getWingsLength()))
a4.move()
print("=====================")
print("Name	                : "+ str (a5.getname()))
print("Age	                : "+ str(a5.getage()))
print("Type	                : "+ str(a5.gettype()))
print("Fuel Type	        : "+ str(a5.getfueltype()))
print("MaxPassengers	        : "+ str(a5.getmaxpassengers()))
print("Wings length     	: "+ str(a5.getWingsLength()))
a5.move()
print("=====================")



